fixes

diff --git a/.github/workflows/check-file-changes.yml b/.github/workflows/check-file-changes.yml
--- a/.github/workflows/check-file-changes.yml
+++ b/.github/workflows/check-file-changes.yml
@@ -20,6 +20,14 @@ jobs:
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
-          for file in ${ALL_CHANGED_FILES}; do
-            echo "$file was changed"
-          done
+          changed_files="${ALL_CHANGED_FILES}"
+          if [ ${ #changed_files[@] } -ne 1 ]; then
+              echo "Error: Array should contain exactly one file name."
+              exit 1
+          fi
+
+          file_name="${ changed_files[0] }"
+          if [[ ! "$file_name" =~ ^app_chains.*\.json$ ]]; then
+              echo "Error: File name does not start with 'app_chains' or does not end with '.json'."
+              exit 1
+          fi
